### ISSUE TITLE
 returned json results from AWS Cloudsearch

### ISSUE THREAD

**Issue by basemwahba** [moappi/json2html#15]
How can json2html handle returned json results from below AWS Cloudsearch html search form:  

    <form action="https://$YOURSEARCHDOMAIN/2013-01-01/search" method="get">
    <label>Search: <input name="q" /></label>
    <input type="hidden" name="q.parser" value="simple" />
    <button type="submit">Search</button>
    </form>

**Comment by moappi** [comment]
Could you post up the json that you're wanting to transform

**Comment by basemwahba** [comment]
{"status":{"rid":"nr6A14Mq/AIK2Eli","time-ms":12},"hits":{"found":200,"start":0,"hit":[{"id":"tt0054189","fields":{"rating":"7.7","genres":["Crime","Thriller"],"title":"Plein soleil","release_date":"1960-03-10T00:00:00Z","plot":"Tom Ripley is a talented mimic, moocher, forger and all-around criminal improviser; but there's more to Tom Ripley than even he can guess.","rank":"3623","running_time_secs":"7080","directors":["René Clément"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTIwNjE5ODA0OV5BMl5BanBnXkFtZTcwNDk4NzAyMQ@@._V1_SX400_.jpg","year":"1960","actors":["Alain Delon","Maurice Ronet","Marie Laforêt"],"_score":"8.213773"},"highlights":{"actors":"Alain Delon Maurice Ronet Marie Laforêt","directors":"René Clément","plot":"*#*Tom*%* Ripley is a talented mimic, moocher, forger and all-around criminal improviser; but there's more to *#*Tom*%* Ripley than even he can guess.","title":"Plein soleil"}},{"id":"tt1583420","fields":{"rating":"5.9","genres":["Comedy","Drama","Romance"],"title":"Larry Crowne","release_date":"2011-06-27T00:00:00Z","plot":"After losing his job, a middle-aged man reinvents himself by going back to college.","rank":"2102","running_time_secs":"5880","directors":["Tom Hanks"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTM1NzAyNTEwN15BMl5BanBnXkFtZTcwODYyNTEzNQ@@._V1_SX400_.jpg","year":"2011","actors":["Tom Hanks","Julia Roberts","Sarah Mahoney"],"_score":"7.676402"},"highlights":{"actors":"*#*Tom*%* Hanks Julia Roberts Sarah Mahoney","directors":"*#*Tom*%* Hanks","plot":"After losing his job, a middle-aged man reinvents himself by going back to college.","title":"Larry Crowne"}},{"id":"tt0117887","fields":{"rating":"6.7","genres":["Comedy","Drama","Music"],"title":"That Thing You Do!","release_date":"1996-09-14T00:00:00Z","plot":"A Pennsylvania band scores a hit in 1964 and rides the star-making machinery as long as it can, with lots of help from its manager.","rank":"2436","running_time_secs":"6480","directors":["Tom Hanks"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTczMzM2MTM0NF5BMl5BanBnXkFtZTcwMTIwMDQ0MQ@@._V1_SX400_.jpg","year":"1996","actors":["Tom Hanks","Liv Tyler","Charlize Theron"],"_score":"7.676402"},"highlights":{"actors":"*#*Tom*%* Hanks Liv Tyler Charlize Theron","directors":"*#*Tom*%* Hanks","plot":"A Pennsylvania band scores a hit in 1964 and rides the star-making machinery as long as it can, with lots of help from its manager.","title":"That Thing You Do!"}},{"id":"tt0240515","fields":{"rating":"4.2","genres":["Comedy"],"title":"Freddy Got Fingered","release_date":"2001-04-18T00:00:00Z","plot":"An unemployed cartoonist moves back in with his parents and younger brother Freddy. When his parents demand he leave, he begins to spread rumors that his father is sexually abusing Freddy.","rank":"3368","running_time_secs":"5220","directors":["Tom Green"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTYxOTI5OTI1OV5BMl5BanBnXkFtZTYwMzY3MjM5._V1_SX400_.jpg","year":"2001","actors":["Tom Green","Rip Torn","Marisa Coughlan"],"_score":"7.676402"},"highlights":{"actors":"*#*Tom*%* Green Rip Torn Marisa Coughlan","directors":"*#*Tom*%* Green","plot":"An unemployed cartoonist moves back in with his parents and younger brother Freddy. When his parents demand he leave, he begins to spread rumors that his father is sexually abusing Freddy.","title":"Freddy Got Fingered"}},{"id":"tt0100258","fields":{"rating":"6.7","genres":["Horror"],"title":"Night of the Living Dead","release_date":"1990-10-19T00:00:00Z","plot":"The unburied dead return to life and seek human victims.","rank":"3858","running_time_secs":"5520","directors":["Tom Savini"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTY3ODQ2NzczNl5BMl5BanBnXkFtZTcwNDg0MjkyMQ@@._V1_SX400_.jpg","year":"1990","actors":["Tony Todd","Patricia Tallman","Tom Towles"],"_score":"7.676402"},"highlights":{"actors":"Tony Todd Patricia Tallman *#*Tom*%* Towles","directors":"*#*Tom*%* Savini","plot":"The unburied dead return to life and seek human victims.","title":"Night of the Living Dead"}},{"id":"tt0066832","fields":{"rating":"5.8","genres":["Action","Drama"],"title":"Billy Jack","release_date":"1971-05-01T00:00:00Z","plot":"Ex-Green Beret hapkido expert saves wild horses from being slaughtered for dog food and helps protect a desert \"freedom school\" for runaway.","rank":"4617","running_time_secs":"6840","directors":["Tom Laughlin"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTkwNTg4MDYwNV5BMl5BanBnXkFtZTcwNjIzMTQyMQ@@._V1_SX400_.jpg","year":"1971","actors":["Tom Laughlin","Delores Taylor","Clark Howat"],"_score":"7.676402"},"highlights":{"actors":"*#*Tom*%* Laughlin Delores Taylor Clark Howat","directors":"*#*Tom*%* Laughlin","plot":"Ex-Green Beret hapkido expert saves wild horses from being slaughtered for dog food and helps protect a desert \"freedom school\" for runaway.","title":"Billy Jack"}},{"id":"tt1179891","fields":{"rating":"5.4","genres":["Horror","Thriller"],"title":"My Bloody Valentine","release_date":"2009-01-08T00:00:00Z","plot":"Tom returns to his hometown on the tenth anniversary of the Valentine's night massacre that claimed the lives of 22 people. Instead of a homecoming, however, Tom finds himself suspected of committing the murders, and it seems like his old flame is the only one will believes he's innocent.","rank":"1886","running_time_secs":"6060","directors":["Patrick Lussier"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTY2MTQ1OTcxOF5BMl5BanBnXkFtZTcwMjc2ODUxMg@@._V1_SX400_.jpg","year":"2009","actors":["Jensen Ackles","Jaime King","Kerr Smith"],"_score":"6.193855"},"highlights":{"actors":"Jensen Ackles Jaime King Kerr Smith","directors":"Patrick Lussier","plot":"*#*Tom*%* returns to his hometown on the tenth anniversary of the Valentine's night massacre that claimed the lives of 22 people. Instead of a homecoming, however, *#*Tom*%* finds himself suspected of committing the murders, and it seems like his old flame is the only one will believes he's innocent.","title":"My Bloody Valentine"}},{"id":"tt0427954","fields":{"rating":"6.9","genres":["Action","Crime","Drama","Thriller"],"title":"Tom yum goong","release_date":"2005-08-11T00:00:00Z","plot":"A young fighter named Kham must go to Australia to retrieve his stolen elephant. With the help of a Thai-born Australian detective, Kham must take on all comers, including a gang led by an evil woman and her two deadly bodyguards.","rank":"4139","running_time_secs":"6480","directors":["Prachya Pinkaew"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTc2NjE0NTA5M15BMl5BanBnXkFtZTcwNTkxNDUzMQ@@._V1_SX400_.jpg","year":"2005","actors":["Tony Jaa","Nathan Jones","Petchtai Wongkamlao"],"_score":"5.9977098"},"highlights":{"actors":"Tony Jaa Nathan Jones Petchtai Wongkamlao","directors":"Prachya Pinkaew","plot":"A young fighter named Kham must go to Australia to retrieve his stolen elephant. With the help of a Thai-born Australian detective, Kham must take on all comers, including a gang led by an evil woman and her two deadly bodyguards.","title":"*#*Tom*%* yum goong"}},{"id":"tt1195478","fields":{"rating":"6.2","genres":["Comedy","Romance"],"title":"The Five-Year Engagement","release_date":"2012-04-27T00:00:00Z","plot":"One year after meeting, Tom proposes to his girlfriend, Violet, but unexpected events keep tripping them up as they look to walk down the aisle together.","rank":"808","running_time_secs":"7440","directors":["Nicholas Stoller"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTk3MDE1NTA3M15BMl5BanBnXkFtZTcwNDcwNTMxNw@@._V1_SX400_.jpg","year":"2012","actors":["Jason Segel","Emily Blunt","Chris Pratt"],"_score":"5.7606945"},"highlights":{"actors":"Jason Segel Emily Blunt Chris Pratt","directors":"Nicholas Stoller","plot":"One year after meeting, *#*Tom*%* proposes to his girlfriend, Violet, but unexpected events keep tripping them up as they look to walk down the aisle together.","title":"The Five-Year Engagement"}},{"id":"tt0100150","fields":{"rating":"7.9","genres":["Crime","Drama","Thriller"],"title":"Miller's Crossing","release_date":"1990-08-01T00:00:00Z","plot":"Tom Regan, an advisor to a Prohibition-era crime boss, tries to keep the peace between warring mobs but gets caught in divided loyalties.","rank":"2621","running_time_secs":"6900","directors":["Joel Coen","Ethan Coen"],"image_url":"http://ia.media-imdb.com/images/M/MV5BMTk2NDIxNzEyNF5BMl5BanBnXkFtZTYwMjk2NTk5._V1_SX400_.jpg","year":"1990","actors":["Gabriel Byrne","Albert Finney","John Turturro"],"_score":"5.7606945"},"highlights":{"actors":"Gabriel Byrne Albert Finney John Turturro","directors":"Joel Coen Ethan Coen","plot":"*#*Tom*%* Regan, an advisor to a Prohibition-era crime boss, tries to keep the peace between warring mobs but gets caught in divided loyalties.","title":"Miller's Crossing"}}]}}

**Comment by moappi** [comment]
var transform = {"tag":"li","html":"${fields.title} ${fields.rating}"};

var html = json2html.transform(json.hits.hit,transform);

// or using jquery plugin
$('ul').json2html(json.hits.hit,transform);

Pretty standard stuff, you can find more in the examples

https://github.com/moappi/json2html/tree/master/examples

or check out http://visualizer.json2html.com to see what json2html can really do
