### ISSUE TITLE
Behavior of 'replace' option in jQuery plugin

### ISSUE THREAD

**Issue by claytonrcarter** [moappi/json2html#20]
In the jQuery plugin, what does the `replace` option do?  The docs on the website (under "Usage / jquery") say "elements will be replace the elements in the source object", which seems to imply that it will empty the source object and fill it back up again, but when I use it, it seems to replace the source element (not just it's children) with the new elements.

I tried it like this:

    $('#list_container > ul').json2html( data.tasks, j2h_task_transform, { replace: true });

I was able to get my desired result by using `empty()` and skipping the `replace` option:

    $('#list_container > ul').empty().json2html( data.tasks, j2h_task_transform );

Is it supposed to replace the source object?

**Comment by voko** [comment]
afaik, works as advertised.

If you select an element like `$('#list_container > ul')`, the `replace()` method will replace each found element (in your case the `<ul>` element), while a call to json2html will change the *content* of the selected element, in your case the `<li>`elements.

I use `replace()` when I want to overwrite an element, usually a placeholder with a specific ID.
I use `json2html()`when I want to add content to an element (e.g. `li` nodes to an `ul` element.)

**Comment by moappi** [comment]
Replace is part of the jquery plugin for json2html and should be logged there [jquery.json2html](https://github.com/moappi/jquery.json2html).

You're correct that the documentation is a little vague on what replace does.  Replace uses the jquery method [replaceWith](http://api.jquery.com/replacewith/).  As voko pointed out replace is used to replace a specific element(s) selected by your jquery query.  Have a look at the jquery documentation for more information.  

In your use case it's probably best to just use .empty().json2html(..) method chain.
