### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by sufuf3** [moappi/json2html#22]
Hi @moappi ,
We are cdnjs team, we're going to host this library.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/moappi/json2html/tags) so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo? Thank you.

[cdnjs/cdnjs#10486](https://github.com/cdnjs/cdnjs/issues/10486)

**Comment by moappi** [comment]
Ok all done .. thanks!
