### ISSUE TITLE
Help add package.json to upstream

### ISSUE THREAD

**Issue by sufuf3** [moappi/json2html#23]
Hi @moappi,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We are going to host this library.
Could you please help me add package.json to upstream?
Thank you.

[cdnjs/cdnjs#10486](https://github.com/cdnjs/cdnjs/pull/10486)

**Comment by moappi** [comment]
Added .. if that looks good I'll add a new release if needed

**Comment by sufuf3** [comment]
Thank you.
It looks good.
