### ISSUE TITLE
help confirm the pull request from cdnjs

### ISSUE THREAD

**Issue by sufuf3** [moappi/json2html#24]
Hi @moappi,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). 
Could you please help confirm this [PR](https://github.com/cdnjs/cdnjs/pull/10486) what you expected? 
(Adding the json2html core? Or you want jquery wrapper?) 
Thanks.

[cdnjs/cdnjs#10486](https://github.com/cdnjs/cdnjs/pull/10486)

**Comment by moappi** [comment]
Ideally both .. json2html core is required when using the jquery wrapper.  So both will need to be hosted.  However, what might be confusing is that I added the json2html core to the jquery wrapper project as an easy way for people to download both without having to also go to the core project and download the core from there.

People do, however, use the core without also using the jquery wrapper.
