### ISSUE TITLE
issue in innerHtml

### ISSUE THREAD

**Issue by rajeshwarKrr** [moappi/json2html#32]
I'm using a json2html for a while in nodejs

this Input I have given 
`<p>Having a hard time figuring <b>out</b> how to create </p>`

I got this

`{"<>":"p","html":[
    {"<>":"b","html":"out"}
  ]}`

but my expected output was something else 

> Text before and after `<b></b>` tag is missing

Can someone please help

**Comment by moappi** [comment]
You'll need to wrap all of your text in html tags.  So something like this will work

`{"<>":"p","html":[  {"<>":"span","text":"Having a hard time figuring "} ,{"<>":"b","text":"out"}, {"<>":"b","text":" how to create"}  ]}`

or you can do this as well

`{"<>":"p","html":"Having a hard time figuring <b>out</b> how to create"}`
