### ISSUE TITLE
Is it possible to generate checked radio buttons?

### ISSUE THREAD

**Issue by shunjid** [moappi/json2html#33]
This **not an issue**. A simple question. Is it possible to generate radio buttons inside table with **checked** attributes? Let's say,

I have a JSON data in which Gender : 1 means Male and Gender : 2 means Female. I want to convert them into a radio button inside a html table within rowspan of 3 rows.

Let's say, the JS Array Of Object which is :

```js
var data = 
[{
  "Gender": 1,
  "Height": [0,0,0],
  "Book": 3
},
{
  "Gender": 2,
  "Height": [0,0,0],
  "Book": 4
}];
```
How do I convert this JSON data to a html table like this with checked radio buttons by using **json2html**?

![Screenshot from 2019-11-24 22-48-34](https://user-images.githubusercontent.com/29749035/69500767-3cb7ac00-0f28-11ea-850d-c648367d791a.png)

**Comment by moappi** [comment]
Yep you can create any type of html element using json2html.  You can create a radio button using a transform like this

```
{"<>":"input","type":"radio","name":"gender-${Book}","value":"male","checked":function(){
                if(this.Gender === 1) return(true);
            }}
```

Note that html attributes aren't included if the value returned is undefined or null, you can use that to set the checked attribute.

Here's how you can do that inside a table

```
{"<>":"tr","html":[
        {"<>":"td","html":[
            {"<>":"input","type":"radio","name":"gender-${Book}","value":"male","checked":function(){
                if(this.Gender === 1) return(true);
            }},
            {"<>":"span","html":"Male"},
            {"<>":"br"},
            {"<>":"input","type":"radio","name":"gender-${Book}","value":"female","checked":function(){
                if(this.Gender === 2) return(true);
            }},
            {"<>":"span","html":"Female"}
        ]},
        {"<>":"td","html":"${Book}"}
]};
```

**Comment by riveruniversity** [comment]
Thank you.
