### ISSUE TITLE
Linking to remote JSON file in Jquery

### ISSUE THREAD

**Issue by KevDoy** [moappi/json2html#34]
No matter how I import a JSON file I can not get it to work - even having the contents be loaded into a variable:
`var data = variable`

This causes errors as well. Is this something that is at all/will be possible in the future?
So far the only way to get around this is to create a javascript file, add `var data=` to the beginning of the data and link it in the HTML file.

**Comment by moappi** [comment]
As long as the object is a valid JSON object json2html will be able to render it irregardless if it was from a JSON file, ajax query or a local object.  

Best to verify that your JSON object is being imported correctly. 

Feel free to post the code here and I'll help debug

**Comment by KevDoy** [comment]
Thank you. I'll give that a try.

**Comment by KevDoy** [comment]
Still having trouble. This is what I have gotten. When I have the data display in an alert, for example, it appears to show up just fine. Copying and pasting the exact json file to var data = *data here* works as well.

Tried hosting the json on a server as well and pointing the url value to it.

```
<script>
var data = $.ajax({ "dataType": "json", "url": "data.json" })
		</script>
<script>

	</script>
<script type="text/javascript">
 

    //List item transform
    var transform = {"<>":"a","href":"/search=${search}","html":[
						{"<>":"div","class":"col-xs-6 col-md-3 coupontile margin-right","html":[
							{'<>':'div',"class":"row pricing",'html':[
								{'<>':'div',"class":"col-md-12",'html':[
									{'<>':'div',"class":"pricing-item",'html':[
										 {"<>":"span","class":"price-dollarSign","html":"&#36;"},
										 {"<>":"span","class":"price-dollar","text":" ${dollar}"},
										 {"<>":"span","class":"price-cents","text":" ${cents}"}
									]},
									{'<>':'div',"class":"pricing-item",'html':[
										 {"<>":"span","class":"price-off","html":"&nbsp;OFF"},
										 {"<>":"span","class":"price-limit","text":" ${limit}"}
									]}
								]}
							]},
						{'<>':'div',"class":"row",'html':[
							{'<>':'div',"class":"col-md-6",'html':[
								 {"<>":"span","class":"brand","text":"${product}"},
								 {"<>":"br"},
								 {"<>":"span","class":"brand-details","text":" ${description}"},
								 {"<>":"br"},
								 {"<>":"br"},
								 {"<>":"span","class":"item-numbers","text":"${item}"},
								 {"<>":"br"},
								 {"<>":"span","class":"item-red-text","text":"${redText}"}
							]},
							{'<>':'div',"class":"col-md-6",'html':[
								 {"<>":"img","class":"img-responsive","src":"/&itemId=${imageFilePath}"}
							]}
						]}
						]}
					 ]};
    $(function(){
        
        //Create the list
        $('#coupons').json2html(data,transform);
    });
</script>

```
![image](https://user-images.githubusercontent.com/11251011/72851251-f187f400-3c5f-11ea-9e50-a3d19263332c.png)

**Comment by moappi** [comment]
You'll need to use the Ajax done callack and put the json2html call there.
Ajax is an asynchronous call.

See more here https://api.jquery.com/jquery.ajax/
https://www.tutorialsteacher.com/jquery/jquery-ajax-method

$.ajax(..).done(callback);

**Comment by KevDoy** [comment]
Appreciate you helping a total noob here. 

I'll see if I can figure this out. Thank you.

**Comment by KevDoy** [comment]
Think you could show me an example? I'm having a hard time wrapping my head around this. 

Also if you have a way to donate, I would love to do that.

**Comment by moappi** [comment]
No way to donate yet .. but it might be something we'll add to www.json2html.com the future!

Here's a little example on how to use $.ajax calls with JSON and json2html

```
$.ajax({
  "dataType": "json",
  "url": "/some/path/data.json"
}).done(function(json){

    if(!json) return alert("No json returned");
    
    $("#someelement").jsonhtml(json,transform);
}).fail(function( jqXHR, textStatus ) {
    alert("Unable to read data.json (" + textStatus + ")" );
});
```

**Comment by KevDoy** [comment]
Oddly getting a parse error no matter what JSON file I use. Even a simple one. 
I'm assuming json2html does .parseJSON for me so there's not reason to add that anywhere? 

![Screen Shot 2020-01-22 at 7 42 20 AM](https://user-images.githubusercontent.com/11251011/72908769-d1e9dd80-3cea-11ea-851d-ebeafa9f1c04.png)
<img width="259" alt="Screen Shot 2020-01-22 at 7 42 37 AM" src="https://user-images.githubusercontent.com/11251011/72908770-d1e9dd80-3cea-11ea-8af6-4eb03a305a90.png">

**Comment by moappi** [comment]
JSON doesn't allow for comments embedded within the document.  So best to remove all the comments. Also json2html doesn't do any parsing as it expects a valid JSON object.

**Comment by KevDoy** [comment]
That totally worked. No more parse error.
Now that that's all running, I need to get json2html to do it's thing.
I noticed this: 
$("#coupons").jsonhtml(json,transform);

does "json" need a variable? Right now I'm just getting a blank page.

**Comment by moappi** [comment]
Yes json is the the JSON object that you're hoping to convert to HTML.  In this case that will come from the ajax call.  Might be worth throwing in some console.log's to see that the json looks like when it's returned from the ajax call and also insure that the html element #coupons exists

**Comment by KevDoy** [comment]
#coupons exists, going the `var data =` route works as it should

I am getting this error however.
![image](https://user-images.githubusercontent.com/11251011/72920366-01561580-3cfe-11ea-88b2-3b48447e1848.png)

**Comment by moappi** [comment]
make sure you have both the jquery.json2html and json2html library file in the your head of the document in this order

<script src="https://cdnjs.cloudflare.com/ajax/libs/json2html/1.3.0/json2html.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.json2html/1.2.0/jquery.json2html.min.js"></script>

**Comment by KevDoy** [comment]
Those are in there, granted they are local, but they're there. 
Any way I can email you what I got?

**Comment by moappi** [comment]
Post it up on https://stackoverflow.com/ with the full code and post up the url here

**Comment by KevDoy** [comment]
Before I did that, I wanted to see now that my JSON file parses properly, if my previous getJSON method would now work and it did!

I can not thank you enough for all of your help. You've given me so much insight. Thank you x1000!

**Comment by seebrown** [comment]
Just realized that you're not spelling it correctly. It's $('#coupon').
json2html(..)

Also check out the examples in https://www.json2html.com
