### ISSUE TITLE
Documentation question: where does 'li' come from

### ISSUE THREAD

**Issue by sjcjoosten** [moappi/json2html#35]
In the documentation on https://json2html.com/docs/#main-attributes-html in the last example in the ``html`` section, the code on line 15 reads:

```
    'parent': {'<>':'div','id':'${id}','html':function(){
```

I believe the `div` here should read `li`. If not, I wouldn't know where the `li` in the example output below it comes from.

Apologies if this is not the place to report this: I couldn't find a repo for the documentation and I'm hoping someone who can edit json2html.com will read this here.

**Comment by moappi** [comment]
Thanks for spotting the error .. yes the line in the example from https://json2html.com/docs/#main-attributes-html  should be

 `'parent': {'<>':'li','id':'${id}','html':function(){`
