### ISSUE TITLE
Events without jquery

### ISSUE THREAD

**Issue by FlokiTV** [moappi/json2html#41]
![image](https://user-images.githubusercontent.com/11356271/128014529-721d9703-4b95-4d4f-b033-3910fdf3cbf5.png)

events dont work if i dont has jquery on page?

![image](https://user-images.githubusercontent.com/11356271/128014656-bd550eee-8cfb-49b3-b11b-053002027aa3.png)

**Comment by moappi** [comment]
Yes that's correct.  In order to use jquery events with json2html you'll need to include jquery as a dependancy.
