### ISSUE TITLE
# in object key

### ISSUE THREAD

**Issue by enricovittorini** [moappi/json2html#44]
nodejs environemnt

I cannot render this object, that have the "#" tag in the name 
```
let d = [
    { "#type": "name", "#value": "Summer" }
  ]
```
in the template i set `"${#type}"`

if I remove the # from the key value, it woks.  How can I support keys with "#".

**Comment by moappi** [comment]
Currently only 0-9 A-Z a-z _  . are allowed when using shorthand notation.  We may look at adding other character support in the future.  

You can use long hand notation for to access any property value like so

{"<>":"span","text":function(){ return(this["#type"]) }}

see the [json2html documentation](https://json2html.com/docs/#main-assignment-inline) for how to use long hand notation
