### ISSUE TITLE
Template Builder executes code before providing JSON format / Source Code available somewhere?

### ISSUE THREAD

**Issue by GalinhaLX** [moappi/json2html#47]
Hi

Providing <script> into  [Template Builder,](https://www.json2html.com/builder/) , executes the script in the page... before rendering it

use case:
```
<script type="text/javascript">
  alert('hi');
</script>

```
executes the code, before providing result

=> Is the source code of [Template Builder,](https://www.json2html.com/builder/) available somewhere? (if open source)

Regards

**Comment by moappi** [comment]
Thanks for picking up on this .. we're hoping to migrate the site to moappi.github.io/json2html, we'd love some help with this if you're interested

**Comment by moappi** [comment]
we added the code for the main website to https://github.com/moappi/moappi.github.io if you're interested in looking into the issue and providing a fix. Plus any help with the docs would be great!
