### ISSUE TITLE
ReferenceError: json2html is not defined in jest test

### ISSUE THREAD

**Issue by cunhabruno** [moappi/json2html#49]
Hello,

I am trying to use node-jsdom2html module from within jest test, but I am getting this error:

```
ReferenceError: json2html is not defined

      1 | import generateReport from "../report-generator";
  >   2 | import * as jsontohtml from '../../node_modules/node-json2html/node.json2html'
        | ^
      3 | import {
      4 |   fullConfig,
      5 |   fullResult,

      at Object.<anonymous> (node_modules/node-json2html/node.json2html.js:18:18)
      at Object.<anonymous> (src/__tests__/index.spec.ts:2:1)
```

I did a demo repository with the code I am trying to execute and I am facing the error: 
https://github.com/cunhabruno/jest-bug-node-json2html/blob/main/__tests__/demo.spec.ts

**Comment by moappi** [comment]
node.json2html.js should only be used for require

Instead if json2html has been added as a dependency in your package.json like so

```
{
  "dependencies": {
    "node-json2html": "2.2.2"
  }
}
```
then you should be able to reference the library like this in your .mjs file

```
import json2html from "node-json2html";

console.log( json2html.render({"var":"test"},{"<>":"span","text":"${var}"}) );
```
