### ISSUE TITLE
What are the technical limitations of the jso2html library?

### ISSUE THREAD

**Issue by codehangen** [moappi/json2html#50]
Hi all! 

I'm thinking of using it jso2html library in a proprietary application that will receive a lot of data. I wonder know where to find information about performance, technical limitations, security techniques and use cases with json2html.  For example, if I use 100,000 data inside a json array, is this library slow?  What are the technical limitations of the jso2html library?

I would be happy with some feedback in this regard.

**Comment by moappi** [comment]
The library has been used in a large number of production environments over the past 10 years or so.  Both Orangedox and dakolor use it extensively. 

As for technical limitations there was a speed benchmark done a number of years back and json2html faired very well in comparison with the other templating libraries at the time.  I would recommend setting up your own benchmarks if you're looking to render 100,000 json objects.  Usually you're going to run into browser issues if you try to render that many html elements on the client.
