### ISSUE TITLE
json2html with emmet?

### ISSUE THREAD

**Issue by codehangen** [moappi/json2html#52]
Hi everyone.

*idea*
A crazy idea I thought of today would be to write parts of the html in emmet and json2html.

*why?*
- This reduces the complexity of developing  html pages like spa(single page application), mpa(multipage application)
- Today it is very common to use the json format as a response to APIs that use the http protocol.  So *this would allow minifying large html into something simple based on emmet and json2html.*

#### input
```css
#page>div.logo+ul#navigation>li*5>a{Item $}
```

#### output
```html
<div id="page">
  <div class="logo"></div>
  <ul id="navigation">
    <li><a href="">Item 1</a></li>
    <li><a href="">Item 2</a></li>
    <li><a href="">Item 3</a></li>
    <li><a href="">Item 4</a></li>
    <li><a href="">Item 5</a></li>
  </ul>
</div>
```

#### concept-input
```javascript
let template = {'<>':'#page>div.logo+ul#navigation>li*5>a{Item $}'};
document.write( json2html.render({},template));
```

#### concept-output
```html
<div id="page">
  <div class="logo"></div>
  <ul id="navigation">
    <li><a href="">Item 1</a></li>
    <li><a href="">Item 2</a></li>
    <li><a href="">Item 3</a></li>
    <li><a href="">Item 4</a></li>
    <li><a href="">Item 5</a></li>
  </ul>
</div>
```

*What do you think of this idea?*

**Comment by moappi** [comment]
Thanks for the idea here.  Since json2html can already do this with template like the following

```
{"<>":"div","id":"page","html":[
    {"<>":"div","class":"logo"},
    {"<>":"ul","id":"navigation","html":[
        {"<>":"li","{}":o=>o.items,"html":[
            {"<>":"a","href":"","text":"Item ${value}"}
          ]}
      ]}
  ]}
```

with a object like {"items":[1,2,3,4]}

I don't really see the need to incorporate emmet, especially since all json2html would be doing would be to simply run an emmet template.
