### ISSUE TITLE
json2html and htmx?

### ISSUE THREAD

**Issue by codehangen** [moappi/json2html#53]
Hi everyone.

Have you all ever thought of adding [htmx](https://htmx.org/) to json2html?

*input*
```javascript
const button = {'<>':'button', 'class':'button', 'hx-get':'https://pokeapi.co/api/v2/pokemon/ditto',' hx-swap':'outerHTML', text:'Click Me'};
document.write(json2html.render({},button));
```

#### output
***output 1***
```html
<button class="button" hx-get="https://pokeapi.co/api/v2/pokemon/ditto" hx-swap="outerHTML">Click Me</button>
```
***output 2***
![image](https://user-images.githubusercontent.com/111701513/215585795-d5ece46d-3e4c-4b2f-ab2a-2beb73b75591.png)

***output 3***
![image](https://user-images.githubusercontent.com/111701513/215586123-ef78ddea-6eab-43b3-a6cd-89280a90c1de.png)

***output 4***
![image](https://user-images.githubusercontent.com/111701513/215586056-c3729972-2fe1-404b-8944-04d09870730a.png)

*why?*
- This allows creating complex applications with json2html and htmx format.
- this allows tighter integration with two open source tools
- this makes life easier for web developers to build websites, webapps: browser-extensions, pwa(progressive-web-application), spa(single-page-application), mpa (multi-page-application) without frameworks(react, vue-js etc)
- that's my question and my last idea what last would like to contribute json2html
- with this feature json2html - we can use http calls with json return to structure web applications through json format, both as a response and as a rendering process.

*question/feedback*
what do you all think of this idea: htmx+json2html?

**Comment by moappi** [comment]
Sure I think there is a use case for using json2html and htmx.  Though I don't think there would be any need to make changes to the core json2html library to accommodate this.  You'd just need to integrate it into two different spots

1) make sure that htmx picks up the new html elements that json2html creates after you render them. 
2) add in a way to use a registered json2html template to render the output eg.

```
<script>
   json2html.component.add("status",{'<>':'span','text':'${status}'});
</script>

<button class="button" hx-get="https://pokeapi.co/api/v2/pokemon/ditto" hx-swap="outerHTML" hx-j2h-componet="status">Click Me</button>
```
