### ISSUE TITLE
Get undefined error

### ISSUE THREAD

**Issue by bsde1234** [moappi/json2html#55]
I tried this project and get undefined error.

https://codepen.io/codepenju/pen/RwYNapP

Also I need the values in table instead of div.

**Comment by moappi** [comment]
First issue is that your data object isn't json, it's a string. Make sure to parse it to json from whatever system you're getting it from using something like

`JSON.parse(...)`

As for a putting this into a table you can use a template like this, it will make a new row in a table for each product

```
{"<>":"table","html":[
      {"<>":"tr","{}":o=>o.products,"html":[
             {"<>":"td","text":"${title}"},
             {"<>":"td","text":"$${price}"}
      ]}
]}
```

with a data object like this

```
{"products":[
     {"title":"Papaya","price":36},
     {"title":"Sweet potato","price":46}
]}
```
