### ISSUE TITLE
It seems that you cannot import JSON files

### ISSUE THREAD

**Issue by alpineyahoo** [moappi/json2html#62]
I wrote `<script type="module"></script>` instead of `<script></script>` in Native JS and this didn't work. Is it possible/available to import json files instead of embedding raw json code inside html?  
Here I would like to do something like this:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/json2html/2.2.3/json2html.min.js"></script>
 
<script type="module">
    
    import data from "./movies.json" assert { type: "json" };
    
    let template = {'<>':'div','html':'${title} ${year}'};
    
    //render
    document.write( json2html.render(data,template) );
    
</script>
```

**Comment by moappi** [comment]
As long as the JSON object is readable by the browser then json2html should be able to use it as the object state for the render. 

Might be good to look into how to import json correctly into your project. Here's something that might help

[How to read json file in JavaScript](https://www.freecodecamp.org/news/how-to-read-json-file-in-javascript/)

**Comment by moappi** [comment]
Closed as outside the scope of library
